# Generated by Django 6.0.7 on 2026-09-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_promotoria', models.CharField(max_length=100)),
                ('descricao_promotoria', models.TextField(blank=True)),
                ('entrancia', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resolucao', models.CharField(max_length=100)),
                ('descricao_resolucao', models.TextField(blank=True)),
                ('prazo_resolucao', models.CharField(blank=True, max_length=50)),
                ('numero_resolucao', models.CharField(blank=True, max_length=50)),
                ('ano_resolucao', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
