# Generated by Django 6.0.7 on 2026-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotorias', '0002_add_relationship_and_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotoria',
            name='descricao_promotoria',
        ),
        migrations.AddField(
            model_name='promotoriaresolucao',
            name='Unidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resolucao',
            name='prazo_resolucao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
