# Generated by Django 6.0.7 on 2026-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotorias', '0003_remove_promotoria_descricao_promotoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
